import type { Metadata } from "next";
import { Archivo_Black, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Web3Provider from "@/providers/Web3Provider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const robotoMono = Roboto_Mono({
  variable: "--font-inter",
  subsets: ["latin"],
});

const archivoBlack = Archivo_Black({
  variable: "--font-archivo-black",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexus Next Template",
  description: "Generated by Avail team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${archivoBlack.variable} antialiased`}
      >
        <Web3Provider>
          <Navbar />
          {children}
          <Footer />
        </Web3Provider>
        <Toaster
          position={"top-center"}
          toastOptions={{
            duration: 5000,
            style: {
              borderRadius: "9999px",
              background: "#5f7161",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
